version: 2.1
orbs:
  node: circleci/node@4.2.1
workflows:
  build-and-test:
    jobs:
      - node/test:
          version: 14.17.2
          pkg-manager: yarn
          run-command: build
          name: build
      - node/test:
          version: 14.17.2
          pkg-manager: yarn
          run-command: test
          name: test
